[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
idenclave = "E7C52ahzQMJB7u9LQmbTtRxYDeHS814HGeWZcWZgkuag"

[programs.devnet]
idenclave = "E7C52ahzQMJB7u9LQmbTtRxYDeHS814HGeWZcWZgkuag"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/malikathaiyab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
