[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.1.22"

[features]
resolution = true
skip-lint = false

[programs.localnet]
idenclave = "GhdfjF2uHkx45jWaLTaHLfTeCoEsnAnyi2ZcsHxpCNha"

[programs.devnet]
idenclave = "GhdfjF2uHkx45jWaLTaHLfTeCoEsnAnyi2ZcsHxpCNha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/malikathaiyab/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
